"""Add multi-tenant models

Revision ID: 1dd2ee1f07cd
Revises: 002_seed_initial_data
Create Date: 2026-01-19 14:25:34.109782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd2ee1f07cd'
down_revision = '002_seed_initial_data'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
