"""add_payroll_module

Revision ID: 678d50de622b
Revises: 003_tax_exemption
Create Date: 2026-01-23 19:22:29.078689

"""
from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision = '678d50de622b'
down_revision = '003_tax_exemption'
branch_labels = None
depends_on = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _upsert_system_setting(key: str, value: str, description: str) -> None:
    dialect = _dialect_name()
    if dialect == "sqlite":
        op.execute(
            sa.text(
                "INSERT OR REPLACE INTO system_settings (key, value, description) "
                "VALUES (:key, :value, :description)"
            ).bindparams(key=key, value=value, description=description)
        )
        return

    if dialect == "postgresql":
        op.execute(
            sa.text(
                "INSERT INTO system_settings (key, value, description) "
                "VALUES (:key, :value, :description) "
                "ON CONFLICT (key) DO UPDATE SET "
                "value = EXCLUDED.value, "
                "description = EXCLUDED.description"
            ).bindparams(key=key, value=value, description=description)
        )
        return

    op.execute(
        sa.text(
            "INSERT INTO system_settings (key, value, description) VALUES (:key, :value, :description)"
        ).bindparams(key=key, value=value, description=description)
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('tc_id_no', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('personnel_type', sa.Enum('RD_PERSONNEL', 'SUPPORT_PERSONNEL', 'INTERN', name='personneltype'), nullable=False),
    sa.Column('education_level', sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'PHD', name='payrolleducationlevel'), nullable=False),
    sa.Column('graduation_field', sa.Enum('ENGINEERING', 'BASIC_SCIENCES', 'OTHER', name='graduationfield'), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_tc_id_no'), 'employees', ['tc_id_no'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('payroll_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_tenant_id'), 'payroll_periods', ['tenant_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('worked_days', sa.Integer(), nullable=True),
    sa.Column('remote_days', sa.Integer(), nullable=True),
    sa.Column('weekend_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('calculated_gross', sa.Float(), nullable=True),
    sa.Column('sgk_base', sa.Float(), nullable=True),
    sa.Column('income_tax_base', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('income_tax_exemption_amount', sa.Float(), nullable=True),
    sa.Column('stamp_tax_exemption_amount', sa.Float(), nullable=True),
    sa.Column('sgk_employer_incentive_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_id'), 'payroll_entries', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_payroll_period_id'), 'payroll_entries', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_tenant_id'), 'payroll_entries', ['tenant_id'], unique=False)

    if _dialect_name() == "postgresql":
        try:
            op.create_foreign_key(None, 'exemption_reports', 'tenants', ['tenant_id'], ['id'])
        except Exception:
            pass

    income_tax_brackets_2026 = [
        {"limit": 110000, "rate": 0.15},
        {"limit": 230000, "rate": 0.20},
        {"limit": 580000, "rate": 0.27},
        {"limit": 3000000, "rate": 0.35},
        {"limit": None, "rate": 0.40},
    ]

    _upsert_system_setting(
        key="income_tax_brackets_2026",
        value=json.dumps(income_tax_brackets_2026),
        description="2026 Gelir Vergisi Dilimleri (Teknokent Bordro)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _dialect_name() == "postgresql":
        try:
            op.drop_constraint(None, 'exemption_reports', type_='foreignkey')
        except Exception:
            pass

    op.execute(sa.text("DELETE FROM system_settings WHERE key = 'income_tax_brackets_2026'"))

    op.drop_index(op.f('ix_payroll_entries_tenant_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_payroll_period_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_payroll_periods_tenant_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_tc_id_no'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
